transitions:
  - [BWC::Initial_, OK, BWC::Main_, Auto]

states:
  BWC::Initial_:
    base: BWC::Initial
    configs:
      autoStartTime: 2.0

  BWC::ConfigWalk_:
    base: BWC::ConfigWalk
    configs:
      footstepList:
        - foot: Left
          footMidpose:
            translation: [0.15, 0.0, 0.0]
          startTime: 2.0
        - footMidpose:
            translation: [0.30, 0.0, 0.0]
        - footMidpose:
            translation: [0.45, 0.0, 0.0]
        - footMidpose:
            translation: [0.60, 0.0, 0.0]
        - footMidpose:
            translation: [0.60, 0.0, 0.0]
        - foot: Right
          footMidpose:
            translation: [0.60, -0.1, 0.0]
        - footMidpose:
            translation: [0.60, -0.1, 0.0]
        - footMidpose:
            translation: [0.60, -0.2, 0.0]
        - footMidpose:
            translation: [0.60, -0.2, 0.0]
        - footMidpose:
            translation: [0.60, -0.3, 0.0]
        - foot: Left
          footMidpose:
            translation: [0.60, -0.3, 0.0]
            rotation: [0.0, 0.0, 0.25]
        - footMidpose:
            translation: [0.60, -0.3, 0.0]
            rotation: [0.0, 0.0, 0.50]
        - footMidpose:
            translation: [0.60, -0.3, 0.0]
            rotation: [0.0, 0.0, 0.75]
        - foot: Right
          footMidpose:
            translation: [0.777917206333, -0.270923072884, 0.0]
            rotation: [0.0, 0.0, 0.4882006122008506]
        - footMidpose:
            translation: [0.910393946568, -0.200567452661, 0.0]
            rotation: [0.0, 0.0, 0.22640122440170118]
        - footMidpose:
            translation: [1.07901323058, -0.264344698281, 0.0]
            rotation: [0.0, 0.0, -0.03539816339744828]
        - footMidpose:
            translation: [1.22891926315, -0.269653313986, 0.0]
            rotation: [0.0, 0.0, -0.29719755119659763]
        - footMidpose:
            translation: [1.34305922386, -0.409195670883, 0.0]
            rotation: [0.0, 0.0, -0.558996938995747]
        - footMidpose:
            translation: [1.34305922386, -0.409195670883, 0.0]
            rotation: [0.0, 0.0, -0.558996938995747]
      refComZList:
        - refComZ: 0.725
          startTime: 8.0
          interpDuration: 1.0
        - refComZ: 0.825
          startTime: 12.0
          interpDuration: 1.0

  BWC::Main_:
    base: Parallel
    states: [BWC::GuiWalk_, BWC::ConfigWalk_]
